version: "3.8"
services:
  BackupTool:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: "npm run start:prod:docker"
